### ISSUE TITLE
Support Bluetooth peripherals.

### ISSUE THREAD

**Issue by rokejulianlockhart** [yast/yast-installation#1075]
I have a Bluetooth mouse. I don't have a USB wireless transceiver. I was able to use my wired keyboard for installation, but some people use entirely wireless keyboards, too, and I'd like to be able to use my mouse for this purpose.

(I realize the folly of purchasing a mouse that doesn't support wired communication, but my Logitech MX Master 3S is the best mouse that I was able to locate.)

A simple section at the start that pairs a mouse or keyboard if necessary (ideally without any user interaction necessary previously to support such entirely wireless nutcases) would be brilliant for those who simply didn't consider this problem when purchasing their peripherals.

**Comment by shundhammer** [comment]
You can do the installation entirely without a mouse; there is keyboard support for everything. Use `Alt` key combinations to move the focus to another widget directly, or use `Tab` to jump through all of them in sequence.

You can do it even without any graphics mode; just select "text mode" from the installation media boot screen. That mode (called _NCurses_) relies completely on keyboard navigation anyway.

What you do need, though, is a keyboard that behaves like a wired one. I have a Logitech K400 that, while wireless, works just out of the box with a little USB receiver; in the BIOS like on Linux. It even has a touchpad.

There are lots of similar keyboards that work without any fancy Bluetooth support by the OS.

**Comment by rokejulianlockhart** [comment]
@shundhammer, twice I haven't. It's only going to become more common, although I'm definitely going to make a point of purchasing a keyboard with both methods available in future.
