### ISSUE TITLE
Update KDE icon in desktop selection

### ISSUE THREAD

**Issue by victorhck** [yast/yast-installation#440]
Hello!

Maybe the KDE icon at the desktop selection in the installation should be updated... The icon looks like a bit KDE 4 era :)
Maybe something more Plasma like that? https://quitter.es/avatar/17041-96-20160617151952.jpeg

**Comment by ancorgs** [comment]
We introduced a new desktop selection (role selection) dialog with no icons, making this no longer relevant. Closing.
