### ISSUE TITLE
Package timeout is set too long

### ISSUE THREAD

**Issue by romulasry** [yast/yast-installation#667]
If this isn't the correct section for this please forward me, thank you.

**Comment by imobachgs** [comment]
Please, report issues using https://bugzilla.opensuse.org. Additionally, we might need more details like describing what is the problem (ideally specifying the steps to reproduce it) and what did you expected. Additionally, attaching YaST logs is a good thing.

Please, check: https://en.opensuse.org/openSUSE:Report_a_YaST_bug

Thanks a lot!
