### ISSUE TITLE
Enabling libyui REST API without startshell=1

### ISSUE THREAD

**Issue by rwx788** [yast/yast-installation#925]
Currently we have to enable libyui REST API in the installer using `startshell=1` option in order to run `extend libyui-rest-api`  command and extend inst-sys with required libraries. See https://github.com/libyui/libyui/tree/master/libyui-rest-api

In openQA integration we have to introduce additional steps, and enabling it is not so problematic like handling start shell before the reboot, as on exotic backends like zVM or powerVM, it's more tricky to communicate with SUT (system under test).

As of now, only viable option is to use DUD files, which also require extra steps. Would be great if we could have a parameter to extend installer without interactive steps, e.g. extend=libyui-rest-api,gdb. We can also have solution which is less generic and enables REST API only.

openQA job example: https://openqa.opensuse.org/tests/latest?arch=x86_64&distri=opensuse&flavor=DVD&machine=64bit&test=RAID0_gpt&version=Tumbleweed#step : you can see `setup_libyui` and `teardown_libyui` steps which we have to conduct in order to use REST API.

**Comment by kobliha** [comment]
Just for the record, I've asked Rodion to summarize the issue here to get better understanding of what is needed and why and then we should help our QA to make their job easier. In fact, it could help us too...

**Comment by ancorgs** [comment]
Having support for generic `extend` sounds like a good idea. And pretty doable, I would say.

**Comment by wfeldt** [comment]
Something along this: https://github.com/openSUSE/linuxrc/pull/250

**Comment by ancorgs** [comment]
@rwx788 the PR implementing support in linuxrc was merged a week ago. Have you had an opportunity to use it in openQA?

**Comment by rwx788** [comment]
> @rwx788 the PR implementing support in linuxrc was merged a week ago. Have you had an opportunity to use it in openQA?

Hi @ancorgs. So far I've only tested manually and it works like a charm, using in openQA will be added in https://progress.opensuse.org/issues/90101 Also, change didn't arrive to TW yet (last time I've checked last week), but we can still prepare PR. Thanks!

**Comment by ancorgs** [comment]
Cool! Closing the issue then.
