### ISSUE TITLE
Unable to change repository locations during online install

### ISSUE THREAD

**Issue by Firstyear** [yast/yast-installation#976]
When installing a machine in an isolated network, it's common to over-ride the "sources" section from grub to specify an alternate download url. However, yast2 does not use this url during the repository initialisation step, and all online repositories are forced to https://download.opensuse.org.

Expected Results:

When a custom source is used from grub, these should be the "base urls" used. Alternately, a method to override this in a custom source would be useful :) 

Thanks!

**Comment by Firstyear** [comment]
Regardless, it should be possible to manually edit these locations flrom the GUI is another aspect. :)

**Comment by lslezak** [comment]
As displayed on the screenshot, the online repositories are read from external resources. The YaST only contains the hardcoded [main index file](https://github.com/yast/skelcd-control-openSUSE/blob/openSUSE-15_3/control/control.openSUSE.xml#L102).

The main installation repository can be changed via the [install](https://en.opensuse.org/SDB:Linuxrc#p_install) boot option, you can also add more repositories with the [addon](https://en.opensuse.org/SDB:Linuxrc#p_addon) option.

IMHO changing the base of all used URLs is a bit dangerous and you would need to have perfect mirrors of the online repositories which is really unusual setup.

If you really need to use local mirrors then either use the `addon` boot option, add the repositories manually or use AutoYaST for automatic installation.

**Comment by kobliha** [comment]
@lslezak I'm against doing that automagically, but on user-request per repo? That seems to be IMO fine. If you really know what you want, then you could...
